version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: debian:unstable
    steps:
      - checkout
      - run:
          name: add apt repositories
          command: cp .circleci/apt-sources-* /etc/apt/sources.list.d/
      - run:
          name: setup apt
          command: cp .circleci/apt-dont-install-recommended /etc/apt/apt.conf.d/
      - run:
          name: update apt repositories
          command: apt-get update
      - run:
          name: install toolchains
          command: apt-get -y install clang-9 g++-9 clang-8 g++-8 clang-7 g++-7 clang-6.0 g++-6
      - run:
          name: clang 9 c++17
          command: ./contbuild.sh clang++-9 c++17
      - run:
          name: clang 9 c++2a
          command: ./contbuild.sh clang++-9 c++2a
      - run:
          name: gcc 9 c++17
          command: ./contbuild.sh g++-9 c++17
      - run:
          name: gcc 9 c++2a
          command: ./contbuild.sh g++-9 c++2a
      - run:
          name: clang 8 c++17
          command: ./contbuild.sh clang++-8 c++17
      - run:
          name: clang 8 c++17
          command: ./contbuild.sh clang++-8 c++17
      - run:
          name: gcc 8 c++17
          command: ./contbuild.sh g++-8 c++17
      - run:
          name: gcc 8 c++17
          command: ./contbuild.sh g++-8 c++17
      - run:
          name: clang 7 c++2a
          command: ./contbuild.sh clang++-7 c++2a
      - run:
          name: clang 7 c++17
          command: ./contbuild.sh clang++-7 c++17
      - run:
          name: gcc 7 c++2a
          command: ./contbuild.sh g++-7 c++2a
      - run:
          name: gcc 7 c++17
          command: ./contbuild.sh g++-7 c++17
      - run:
          name: clang 6 c++17
          command: ./contbuild.sh clang++-6 c++17
      - run:
          name: clang 6 c++2a
          command: ./contbuild.sh clang++-6 c++2a
      - run:
          name: gcc 6 c++17
          command: ./contbuild.sh g++-6 c++17
      - run:
          name: gcc 6 c++2a
          command: ./contbuild.sh g++-6 c++2a
